### ISSUE TITLE
师傅无法利用啊，会报[!]:LegacyDN not found!。。

### ISSUE THREAD

**Issue by qiaomu2333** [p0wershe11/ProxyLogon#1]
客户说没修。。。我这个用户也是有的

**Comment by p0wershe11** [comment]
You can use burpsuite to grab data packets and manually verify which step is wrong. From the information you gave, I guess that the target mailbox does not exist.

**Comment by qiaomu2333** [comment]
i cat make this email is exist,because i'm using this mailbox,and i can use proxylogon read the domain name.............

**Comment by p0wershe11** [comment]
Can you post some pictures for me to see?

**Comment by xiaozhaha** [comment]
![image](https://user-images.githubusercontent.com/48639007/113395785-fa7c6580-93cc-11eb-86e6-c499057b8cd1.png)

**Comment by mcam1551** [comment]
It depends on the mailbox, for example, if it was a migration from '03 to '10, Changing the legacyExchangeDN will break exchange. A workaround might be copying the existing legacyExchangeDN and then adding it to the account as an custom X500 email address, you might be able to use the mailbox in owa but outlook would be broken, etc etc.

**Comment by bingo007** [comment]
Log.info(f"OAB Name = f{identity['DisplayName']}")
